openapi: 3.1.0
info:
  description: Lightup Metrics API provides CRUD interface to Dashboard objects.
  title: Lightup Dashboard API Credentials API
  version: 1.0.0
servers:
- description: Enter your Lightup subdomain
  url: https://app.{clusterId}.lightup.ai
  variables:
    clusterId:
      default: demo
tags:
- name: API Credentials
paths:
  /api/v1/token/refresh/:
    summary: Get access token
    post:
      description: ''
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              additionalProperties: false
              properties:
                refresh:
                  description: Refresh token that you got from Lightup UI
                  title: Refresh
                  type: string
              required:
              - refresh
              title: TokenRefreshRequestBody
              type: object
        description: ''
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                additionalProperties: false
                properties:
                  access:
                    description: Access token to be used with other API endpoints
                    title: Access
                    type: string
                required:
                - access
                title: TokenRefreshResponse
                type: object
          description: ''
      summary: Get access token
      tags:
      - API Credentials
